const menu = [{
    path: '/index',
    key: 'index',
    name: '主页',
}, {
    path: '/plan',
    key: 'plan',
    name: '资金方案'
}, {
    path: '/topup',
    key: 'topup',
    name: '充值'
}, {
    path: '/withdrawal',
    key: 'withdrawal',
    name: '提现'
}, {
    path: '/moneyWater',
    key: 'moneyWater',
    name: '资金流水',
    filter: [],
    needTime: { key: 'create_time', value: 'RANGE' }
}, {
    path: '/mIndex',
    key: 'mIndex',
    name: '首页',
}, {
    path: '/deposit/:id',
    key: 'deposit',
    name: '策略',
}, {
    path: '/strategy/:id',
    key: 'strategy',
    name: '策略',
}, {
    path: '/usercenter',
    key: 'usercenter',
    name: '个人中心',
}, {
    path: '/userdetail',
    key: 'userdetail',
    name: '个人详情',
}, {
    path: '/capitalflow',
    key: 'capitalflow',
    name: '资金流水',
}, {
    path: '/card/:id',
    key: 'card',
    name: '银行卡信息',
}, {
    path: '/recharge',
    key: 'recharge',
    name: '充值',
}, {
    path: '/bankcard',
    key: 'bankcard',
    name: '充值信息确认',
}, {
    path: '/tixian',
    key: 'tixian',
    name: '提现',
}, {
    path: '/transfer',
    key: 'transfer',
    name: '人民币提现',
}, {
    path: '/ercode',
    key: 'ercode',
    name: '邀请码',
}];

export const MENU = menu;
